import type { Asset, ScenarioInputs, ScenarioResult } from "../lib/api";
import { downloadText, parseSingleRowCsv, toCsv } from "../lib/csv";

export function DataExchange({
  inputs,
  onImportInputs,
  result,
  assets,
}: {
  inputs: ScenarioInputs;
  onImportInputs: (inputs: ScenarioInputs) => void;
  result: ScenarioResult | null;
  assets: Asset[];
}) {
  const exportInputs = () => {
    downloadText("asset-pulse-scenario-inputs.csv", toCsv([inputs]));
  };

  const exportCashFlow = () => {
    if (!result) return;
    const rows = result.monthly.months.map((month, i) => ({
      asset_name: result.asset_name,
      month,
      net_revenue: result.monthly.net_revenue[i],
      opex: result.monthly.opex[i],
      sustaining_capex: result.monthly.sustaining_capex[i],
      dev_capex: result.monthly.dev_capex[i],
      abandonment: result.monthly.abandonment[i],
      free_cash_flow: result.monthly.free_cash_flow[i],
      oil_bbl: result.monthly.oil_bbl[i],
      gas_mcf: result.monthly.gas_mcf[i],
      water_bbl: result.monthly.water_bbl[i],
    }));
    downloadText("asset-pulse-cash-flow-export.csv", toCsv(rows));
  };

  const exportAssets = () => {
    const rows = assets.map((asset) => ({
      id: asset.id,
      name: asset.name,
      asset_type: asset.asset_type,
      region: asset.region ?? "",
      initial_oil_bopd: asset.cost_profile?.decline_inputs?.initial_oil_bopd ?? "",
      annual_decline: asset.cost_profile?.decline_inputs?.annual_decline ?? "",
      fixed_opex_per_month: asset.cost_profile?.opex_inputs?.fixed_opex_per_month ?? "",
      capex_inputs_json: asset.cost_profile?.capex_inputs ? JSON.stringify(asset.cost_profile.capex_inputs) : "",
      metadata_json: asset.metadata ? JSON.stringify(asset.metadata) : "",
    }));
    downloadText("asset-pulse-asset-register.csv", toCsv(rows));
  };

  const importInputs = async (file: File | null) => {
    if (!file) return;
    const text = await file.text();
    const row = parseSingleRowCsv(text);
    const next: ScenarioInputs = { ...inputs };
    for (const [key, value] of Object.entries(row)) {
      if (!(key in next)) continue;
      if (key === "asset_name" || key === "decline_model") {
        (next as unknown as Record<string, string>)[key] = value;
      } else if (key === "apply_economic_limit") {
        (next as unknown as Record<string, boolean>)[key] = value.toLowerCase() === "true";
      } else {
        const n = Number(value);
        if (!Number.isNaN(n)) (next as unknown as Record<string, number>)[key] = n;
      }
    }
    onImportInputs(next);
  };

  return (
    <div>
      <div className="console" style={{ minHeight: 120 }}>
        <span className="ln pre">Asset Pulse // data exchange</span>
        <span className="ln">Export scenario assumptions for Excel review, import edited one-row CSV assumptions, or export monthly cash flow after a scenario run.</span>
        <span className="ln dim">CSV import accepts the same column names generated by “Export scenario inputs”.</span>
      </div>

      <div className="exchange-grid">
        <button className="primary" onClick={exportInputs}>Export scenario inputs</button>
        <button onClick={exportCashFlow} disabled={!result}>Export cash flow</button>
        <button onClick={exportAssets} disabled={assets.length === 0}>Export asset register</button>
        <label className="file-import">
          Import scenario CSV
          <input
            type="file"
            accept=".csv,text/csv"
            onChange={(e) => {
              void importInputs(e.target.files?.[0] ?? null);
              e.currentTarget.value = "";
            }}
          />
        </label>
      </div>
    </div>
  );
}
